version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend-flask
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend-nginx
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: alfajores_db
      MYSQL_USER: administrador
      MYSQL_PASSWORD: Hola123456789
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app-network:

volumes:
  db_data:
